$('#stormBlanc').attr('title','Pas facile la vie de Stormtrooper');
$('#stormBlanc').attr('img','image d’un stormtrooper blanc');
$('#stormBlanc').attr('src','images/nouveauStorm.jpeg');
$('#fontAChanger').attr('class','fas fa-fighter-jet fa-4x');
$('.row4 h1').css('font-size','4rem');
$('.row4 h1').html('Vive les Stormtroopers');
$('.orange').css('opacity', '.8');
$('.fondNoir').css('background-color','#696969');
$('.fondBlanc').css('background-color','#E0E0E0');
$('.parallax3 p').html('Père de Luke Skywalker');
$('.parallax2').hide('h1');
